version: '1.0'
services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  backend:
    # image: "backend"
    # builds the image instead of using the build one.
    build: .
    container_name: backend_application
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017

volumes:
  mongodb_data: